apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workflow-ref-hg38-dev ## This is where the ref genome is saved. #mounted at /ref-hg38
  namespace: argo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: rook-cephfs
---
