apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrkflw-tools
  namespace: argo
  labels:
    app: wrkflw-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrkflw-tools
  template:
    metadata:
      labels:
        app: wrkflw-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: mgbio-cred
      - name: mcdb-bot
      containers:
      - name: wrkflw-tools
        image: docker.cancerdb.io/mcdb-bots/bootstrap:mgbio #docker.cancerdb.io/mgbio-workflow/hla-phlat:1.0.0 #docker.cancerdb.io/mcdb-bots/bootstrap:mgbio
        #resources:
        #  requests:
        #    memory: "60Gi"
        #    cpu: "50"
        #  limits:
        #    memory: "600Gi"
        #    cpu: "50"
        env:
      #   - name: SMPLE
      #     value: "mcdb006-normal-exome"
      #   - name: BAM
      #     value: "/data/output/mcdb006/normal_mcdb006.bam"
      #   - name: REF_FILE
      #     value: "/ref-hg38/reference_genome/all_sequences.fa"
        - name: EPITOPE_LENGTH
          value: "8,9,10,11"
        - name: THREADS
          value: "8"
        - name: NRML_SMPL_NME
          value: "mcdb005-normal-exome"
        - name: PHASED_VCF
          value: "/data/output/mcdb005/phasevcf/mcdb005_phased.vcf.gz"
        - name: INPUT_VCF
          value: "/data/output/mcdb005/pvacseq/transcript_annotated.expression.vcf.gz"
        - name: TUMR_SMPL_NME
          value: "mcdb005-tumor-exome"
        - name: ALLELES
          value: "/data/output/mcdb005/hla/hla_calls/combined_calls.txt"
        - name: PREDICTION_ALGO
          value: "NetMHC NetMHCcons PickPocket SMM SMMPMBEC MHCflurry MHCnuggetsI NetMHCpan NetMHCIIpan SMMalign NNalign MHCnuggetsII"
        - name: OUTPUTDIR
          value: "/data/output/mcdb005/pvac-final"
        - name: BINDING_THRSHLD
          value: "500"
        - name: DWNSTREAM_SQ_LNGTH
          value: "100"
        - name: MIN_FOLD_CHNGE
          value: "1.0"
        - name: NET_CHOP_MTHD
          value: "cterm"
        - name: PEP_SEQ_LNGTH
          value: "21"
        - name: TOP_SCORE_MTRC
          value: "lowest"
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /ref-hg38
            name: workflow-ref-hg38-dev
          # - mountPath: /data
          #   name: workflow-data-dev
      hostNetwork: true
      volumes:
      - name: workflow-ref-hg38-dev
        persistentVolumeClaim:
          claimName: workflow-ref-hg38-dev
          readOnly: false
      # - name: workflow-data-dev
        # persistentVolumeClaim:
          # claimName: immuno-data-pvc-mcdb007
          # readOnly: false
