apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrkflw-tools
  namespace: argo
  labels:
    app: wrkflw-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrkflw-tools
  template:
    metadata:
      labels:
        app: wrkflw-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: mgbio-cred
      - name: mcdb-bot
      containers:
      - name: wrkflw-tools
        image: docker.cancerdb.io/mcdb-bots/bootstrap:mgbio
        #resources:
        #  requests:
        #    memory: "60Gi"
        #    cpu: "50"
        #  limits:
        #    memory: "600Gi"
        #    cpu: "50"
        env:
        - name: EPITOPE_LENGTH
          value: "8,9,10,11"
        - name: THREADS
          value: "8"
        - name: NRML_SMPL_NME
          value: "mcdb001-normal-exome"
        - name: PHASED_VCF
          value: "/data/output/phasevcf/mcdb001_phased.vcf.gz"
        - name: INPUT_VCF
          value: "/data/output/pvacseq/annotated.expression.vcf.gz"
        - name: TUMR_SMPL_NME
          value: "mcdb001-tumor-exome"
        - name: ALLELES
          value: "/data/output/hla/hla_calls/consensus_calls.txt"
        - name: PREDICTION_ALGO
          value: "NetMHC"
        - name: OUTPUTDIR
          value: "/data/output"
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /ref-hg38
            name: workflow-ref-hg38-dev
          - mountPath: /data
            name: workflow-data-dev
      hostNetwork: true
      volumes:
      - name: workflow-ref-hg38-dev
        persistentVolumeClaim:
          claimName: workflow-ref-hg38-dev
          readOnly: false
      - name: workflow-data-dev
        persistentVolumeClaim:
          claimName: immuno-data-pvc-mcdb000
          readOnly: false
