apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrkflw-tools
  namespace: argo
  labels:
    app: wrkflw-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrkflw-tools
  template:
    metadata:
      labels:
        app: wrkflw-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: mgbio-cred
      containers:
      - name: wrkflw-tools
        image: docker.cancerdb.io/mgbio-workflow/hisat2-align:1.0.0
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /ref-hg38
            name: workflow-ref-hg38-dev
          - mountPath: /data
            name: workflow-data-dev
      hostNetwork: true
      volumes:
      - name: workflow-ref-hg38-dev
        persistentVolumeClaim:
          claimName: workflow-ref-hg38-dev
          readOnly: false
      - name: workflow-data-dev
        persistentVolumeClaim:
          claimName: immuno-data-pvc
          readOnly: false
