apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrkflw-tools
  namespace: argo
  labels:
    app: wrkflw-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrkflw-tools
  template:
    metadata:
      labels:
        app: wrkflw-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: mgbio-cred
      - name: mcdb-bot
      containers:
      - name: wrkflw-tools
        image: docker.cancerdb.io/mcdb-bots/fastq-bam:1.0.0
        #resources:
        #  requests:
        #    memory: "60Gi"
        #    cpu: "50"
        #  limits:
        #    memory: "600Gi"
        #    cpu: "50"
        env:
        - name: FASTQR1
          value: "/data/samples/normal-exome/r1.fastq.gz"
        - name: FASTQR2
          value: "/data/samples/normal-exome/r2.fastq.gz"
        - name: DATATYPE
          value: "normal-exome"
        - name: OUTPUTDIR
          value: "/data/output"
        - name: SAMPLEID
          value: "mcdbtest"
        - name: PLATFORMUNIT
          value: "HJC52BBXX.1l"
        - name: PLATFORM
          value: "illuminal"
        - name: SEQHOUSE
          value: "Psomagen"
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /ref-hg38
            name: workflow-ref-hg38-dev
          - mountPath: /data
            name: workflow-data-dev
      hostNetwork: true
      volumes:
      - name: workflow-ref-hg38-dev
        persistentVolumeClaim:
          claimName: workflow-ref-hg38-dev
          readOnly: false
      - name: workflow-data-dev
        persistentVolumeClaim:
          claimName: immuno-data-pvc-mcdbtest
          readOnly: false
