apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrkflw-tools
  namespace: argo
  labels:
    app: wrkflw-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrkflw-tools
  template:
    metadata:
      labels:
        app: wrkflw-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: mgbio-cred
      containers:
      - name: wrkflw-tools
        image: docker.cancerdb.io/mgbio-workflow/pindel:1.4.2
        env:
        - name: CANCERBAM
          value: "/data/output/cancer_final/cancer_0.bam"
        - name: NORMALBAM
          value: "/data/output/normal_final/normal_0.bam"
        - name: INSRTSIZE
          value: "400"
        - name: CANCERNAME
          value: "H_NJ-HCC1395-HCC1395"
        - name: NORMALNAME
          value: "H_NJ-HCC1395-HCC1395_BL"
        - name: REF
          value: "/ref-hg38/reference_genome/all_sequences.fa"
        - name: CHROMO
          value: "ALL"
        - name: OUTPUTDIR
          value: "/data/output"
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /ref-hg38
            name: workflow-ref-hg38-dev
          - mountPath: /data
            name: workflow-data-dev
      hostNetwork: true
      volumes:
      - name: workflow-ref-hg38-dev
        persistentVolumeClaim:
          claimName: workflow-ref-hg38-dev
          readOnly: false
      - name: workflow-data-dev
        persistentVolumeClaim:
          claimName: immuno-data-pvc-0
          readOnly: false
