#!/bin/bash

##Env vars
## FASTQR1
## FASTQR2
## OUTPUTDIR
## DATATYPE
## SAMPLEID
## PLATFORMUNIT HJC52BBXX.1
## PLATFORM illumina
## SEQHOUSE Psomagen

set -o pipefail
set -o errexit

/usr/bin/java -Xmx10g -jar /usr/picard/picard.jar FastqToSam FASTQ=$FASTQR1 FASTQ2=$FASTQR2 OUTPUT="$OUTPUTDIR/samples/$DATATYPE/$SAMPLEID-$DATATYPE.bam" \
SAMPLE_NAME=$SAMPLEID-$DATATYPE LIBRARY_NAME=$SAMPLEID-$DATATYPE PLATFORM_UNIT=$PLATFORMUNIT PLATFORM=$PLATFORM \
SEQUENCING_CENTER=$SEQHOUSE 1>$OUTPUTDIR/output/logs/$SAMPLEID-$DATATYPE.FastqToBam.stdout 2>$OUTPUTDIR/output/logs/$SAMPLEID-$DATATYPE.FastqToBam.stderr
